
server:
  port: 7001
spring:
  application:
    name: cloudstream-kafka
  cloud:
    function:
      definition: stringSupplier;sanitizingConsumer
    stream:
      default-binder: kafka
      bindings:
        stringSupplier-out-0:
          destination: batch-in
        sanitizingConsumer-in-0:
          destination: sanitized-event

      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          sanitizingConsumer-in-0:
            consumer:
              configuration:
                # Forces consumer to wait 5 seconds before polling for messages
                fetch.max.wait.ms: 5000
                fetch.min.bytes: 1000000000
                max.poll.records: 10000000


